config/routes.rb
Rails.application.routes.draw do
  resources :memory_lists
  resources :memory_lists do
  	resources :memory_items
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "memory_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/memory_item.rb
class MemoryItem < ApplicationRecord
  belongs_to :memory_list, optional: true
  validates :content, presence: true
end

app/models/memory_list.rb
class MemoryList < ApplicationRecord
	has_many :memory_items
end

app/controllers/application_controller.rb
#TODO: Move API keys to env variables instead of hard-coded strings
class ApplicationController < ActionController::Base
	def get_real_ip
		if request.remote_ip === '127.0.0.1'
			return '189.6.22.151'
		else 
			return request.remote_ip
		end
	end

	def get_location_info_for_ip
		user_ip_addr = get_real_ip
		# TODO: Move API access_key to env variable
		location_for_ip = RestClient.get "http://api.ipstack.com/" + user_ip_addr + "?access_key=ee44ee6ab733dbb5eec01fd1588e3430"
		info = JSON.parse location_for_ip
		return info
	end

	def get_city_for_ip
		info = get_location_info_for_ip
		if info['city'].present?		
			return info['city']
		else
			return 'City not found'
		end
	end

	def get_latitude_longitude_for_ip
		info = get_location_info_for_ip
		return info['latitude'], info['longitude']
	end 

	# we get climate by lat and long instead of city name or ID in order to avoid duplicates errors or record not found incompatibilities
	# between third-party APIs
	def get_weather_for_latitude_longitude
		latitude, longitude = get_latitude_longitude_for_ip
		if !(latitude.present?) or !(longitude.present?)
			return "Climate couldn't be determined: Lack of information"
		else
			weather_based_on_lat_long = RestClient.get "https://api.openweathermap.org/data/2.5/weather?lat=" + latitude.to_s + "&lon=" + longitude.to_s + "&appid=7bcc10712fe906ecd190ba0bea2c910e"
			info = JSON.parse weather_based_on_lat_long
			return info['weather'][0]['main'] + ", " + info['weather'][0]['description']
		end
	end
	
	# TODO: take care of edge cases e.g 'São Paulo'
	def get_weather_for_city(location)
		endpoint = "https://api.openweathermap.org/data/2.5/weather?q=" + location + "&appid=7bcc10712fe906ecd190ba0bea2c910e"
		begin
			weather_based_on_city = RestClient.get endpoint
		rescue => e
			return e.response
		end 
		info = JSON.parse weather_based_on_city
		#checks if we got a 404 for a city that doesn't exist
		if !(info['cod'].present?)
		 	return "Couldn't find city"
		else 
			return info['weather'][0]['main'] + ", " + info['weather'][0]['description']
		end 
	end
end

app/controllers/memory_items_controller.rb
class MemoryItemsController < ApplicationController
	before_action :set_memory_list

	def create
		location = params[:memory_item][:location]
		weather = params[:memory_item][:weather]
		if (params[:memory_item][:content].empty?)
			flash[:error] = "Content should not be empty"
			redirect_to @memory_list
		end
		if (location.empty?) and (weather.empty?)
			params[:memory_item][:weather] = get_weather_for_latitude_longitude
			params[:memory_item][:location] = get_city_for_ip
		end
		if !(location.empty?) and (weather.empty?)
			params[:memory_item][:weather] = get_weather_for_city(location)
		end
		@memory_item = @memory_list.memory_items.create(memory_item_params)
		redirect_to @memory_list
	end

	def destroy
		@memory_item = @memory_list.memory_items.find(params[:id])
		if @memory_item.destroy
			flash[:success] = "Memory List item was deleted"
		else
			flash[:error] = "Memory List item could not be deleted"
		end
		redirect_to @memory_list
	end

	private

	def set_memory_list
		@memory_list = MemoryList.find(params[:memory_list_id])
	end

	def memory_item_params
		params[:memory_item].permit(:content, :location, :weather, :date_recorded)
	end
end

app/controllers/memory_lists_controller.rb
class MemoryListsController < ApplicationController
  before_action :set_memory_list, only: [:show, :edit, :update, :destroy]

  # GET /memory_lists
  # GET /memory_lists.json
  def index
    @memory_lists = MemoryList.all
  end

  # GET /memory_lists/1
  # GET /memory_lists/1.json
  def show
  end

  # GET /memory_lists/new
  def new
    @memory_list = MemoryList.new
  end

  # GET /memory_lists/1/edit
  def edit
  end

  # POST /memory_lists
  # POST /memory_lists.json
  def create
    @memory_list = MemoryList.new(memory_list_params)

    respond_to do |format|
      if @memory_list.save
        format.html { redirect_to @memory_list, notice: 'Memory list was successfully created.' }
        format.json { render :show, status: :created, location: @memory_list }
      else
        format.html { render :new }
        format.json { render json: @memory_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memory_lists/1
  # PATCH/PUT /memory_lists/1.json
  def update
    respond_to do |format|
      if @memory_list.update(memory_list_params)
        format.html { redirect_to @memory_list, notice: 'Memory list was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory_list }
      else
        format.html { render :edit }
        format.json { render json: @memory_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memory_lists/1
  # DELETE /memory_lists/1.json
  def destroy
    @memory_list.destroy
    respond_to do |format|
      format.html { redirect_to memory_lists_url, notice: 'Memory list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory_list
      @memory_list = MemoryList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_list_params
      params.require(:memory_list).permit(:title, :description, :date_created)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memory_items_helper.rb
module MemoryItemsHelper
end

app/helpers/memory_lists_helper.rb
module MemoryListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dumbledore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/memory_items/_form.html.erb
<div class="card" style="margin: 5%">
<%= form_for([@memory_list, @memory_list.memory_items.build],:html => { :style => 'padding:2%;' }) do |f| %>
	<form style="padding: 5%">
		<div class="form-group">
		    <label for="content"><%= f.label :content %></label>
		    	<%= f.text_field :content, class: "form-control required", placeholder: "New Memory" %>
		</div>
		<div class="form-group">
		    <label for="location"><%= f.label :location %></label>
		  	<%= f.text_field :location, class: "form-control", placeholder: "Headmaster's Room" %>
		</div>
		<div class="form-group">
		    <label for="weather"><%= f.label :weather %></label>
		    <%= f.text_field :weather, class: "form-control", placeholder: "It's raining Death Eaters" %>
		</div>
		<div class="form-group">
			<label for="Select date"><%= f.label :date_recorded %></label>
		 	<%= f.datetime_select :date_recorded %>
		</div>
		<center>
	 	<button type="submit" class="btn btn-primary btn-lg" name="commit" style="background-color: #ff4081; margin: 2%;"> Submit</button>
	 	</center>
	</form>
<% end %>
</div>
 

app/views/memory_items/_memory_item.html.erb
<p><i> Memory: </i></p>
<p><%= memory_item.content %></p>
<p><i> Location: </i></p>
<p><%= memory_item.location %></p>
<p><i> Weather: </i></p>
<p><%= memory_item.weather %></p>
<p><i> Date Recorded: </i></p>
<p><%= memory_item.date_recorded %></p>
<%= link_to "Remove memory from Pensieve", memory_list_memory_item_path(@memory_list, memory_item.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/memory_lists/_form.html.erb
<div class="card" style="margin: 5%">
<%= form_for(@memory_list,:html => { :style => 'padding:2%;' }, :url => memory_lists_path, method: :post) do |form| %>  
<form style="padding: 5%">
  <div class="form-group">
    <label for="title"><%= form.label :title %></label>
    <%= form.text_field :title, class: "form-control required", placeholder: "Memory List Title" %>
  </div>

  <div class="form-group">
    <label for="description"><%= form.label :description %></label>
    <%= form.text_area :description, class: "form-control required", placeholder: "Memory List description" %>
  </div>

    <div class="form-group">
      <label for="Select date"><%= form.label :date_created %></label>
      <%= form.datetime_select :date_created %>
    </div>

    <button type="submit" class="btn btn-primary btn-lg" name="commit" style="background-color: #ff4081; margin: 2%;"> Submit</button>
    </center>

    </center>
  </form>
<% end %>
</div>

app/views/memory_lists/edit.html.erb
<h1>Editing Memory List</h1>

<%= render 'form', memory_list: @memory_list %>

<%= link_to 'Show', @memory_list %> |
<%= link_to 'Back', memory_lists_path %>

app/views/memory_lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="dumbledore text-center">Dumbledore's Pensieve</div>

<center>
  <img src="/dumbledore.jpg" style="max-width:50%;
  max-height:50%;">

  <blockquote class="blockquote" style="margin: 5%">
    <p class="mb-0">I use the Pensieve. One simply siphons the excess thoughts from one's mind, pours them into the basin, and examines them at one's leisure. It becomes easier to spot patterns and links, you understand, when they are in this form.</p>
    <footer class="blockquote-footer">Albus Dumbledore <cite title="Source Title">Harry Potter and the Globet of Fire</cite></footer>
  </blockquote>
<center>
<table class="table">
  <thead>
    <tr>
      <th>Memory List</th>
      <th>Description</th>
      <th>Date created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memory_lists.each do |memory_list| %>
      <tr>
        <td><%= memory_list.title %></td>
        <td><%= memory_list.description %></td>
        <td><%= memory_list.date_created %></td>
        <td><%= link_to 'Show', memory_list %></td>
        <td><%= link_to 'Destroy', memory_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Memory List', new_memory_list_path %>
</button>
</center>

app/views/memory_lists/new.html.erb
<div style="margin:3%;""><center><h1>New Memory List</h1></center></div>

<%= render 'form', memory_list: @memory_list %>

<%= link_to 'Back', memory_lists_path %>

app/views/memory_lists/show.html.erb
<p id="notice"><%= notice %></p>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= memory_lists_path %>">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page"> <%= @memory_list.title %></li>
  </ol>
</nav>
<div class="row">
	<div class="col">
			<i>Memory list details:</i> <%= @memory_list.description %>
	</div>
	<div class="col">
		  <div class="text-right"><i>Memory list created on:</i> <%= @memory_list.date_created %> </div>
	</div>
</div>
<!-- <div id="memory_items_wrapper">
 -->
<% @memory_list.memory_items.each do |memory_item| %>
	<div class="card" style="margin: 5%">
	  <h5 class="card-header text-center"><i><%= memory_item.location %></i></h5>
	  <div class="card-body">
	    <h5 class="card-title text-center"><%= memory_item.content %></h5>
	    <p class="card-text text-right">Weather: <i><%= memory_item.weather %></i></p>
	    <p class="card-text text-right">Created on: <i><%= memory_item.date_recorded %></i></p>
        <td class="pull-right"><%= link_to 'Delete Memory', memory_list_memory_item_path(:memory_list_id => @memory_list.id, :id => memory_item.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </div>
	</div>
<% end %>
 <div id="form">
  <%= render "memory_items/form" %>
 </div>
</div>